language: android
os: linux
dist: focal
jdk: oraclejdk8
services: docker
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution
cache:
  directories:
    - "$HOME/.gradle/caches"
    - "$HOME/.gradle/wrapper"
    - "$HOME/.android/build-cache"
env:
  global:
    - ANDROID_API=30
    - ANDROID_BUILD_TOOLS=30.0.0
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - openssl aes-256-cbc -K $encrypted_d51807034090_key -iv $encrypted_d51807034090_iv
    -in keys.properties.enc -out keys.properties -d
  - openssl aes-256-cbc -K $encrypted_6a5a7dcc4b06_key -iv $encrypted_6a5a7dcc4b06_iv
    -in keys.jks.enc -out keys.jks -d
  - openssl aes-256-cbc -K $encrypted_fd8d34b142d0_key -iv $encrypted_fd8d34b142d0_iv
    -in google-services.json.enc -out app/google-services.json -d
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - chmod +x gradlew
  - "./gradlew dependencies || true"
